import React from 'react'

const AboutPage = () => {
    const aboutBlurbParas = [
        "I’m a software developer in the renewable energy sector, currently creating web based plugins used to monitor real-time data in custom micro-grid setups.",
        "My love for learning and solving problems with the skills that I learn are what motivate me as a software developer. I am always interested in finding out how things work under the hood and thoroughly enjoy getting stuck deep in the documentation.",
        "I started out as a teacher, I studied Mathematics and Physics Education and taught these subjects for two years at a high school level. After two years of teaching I had the opportunity to create online Physical Science learning materials for the UCT Online High School. ",
        "Creating online content led me to realise my passion for software. This was a result of me writing simple HTML, CSS and some JavaScript for two years while creating content on the Moodle Learning Management platform.",
        "This passion evolved and I pursued a full stack web development bootcamp in my spare time to learn how to write production level JavaScript code.",
        "I finally found a position at a renewable energy monitoring and control company and have now written software that lets clients visualise data generated by their micro-grid plants.",
        "In addition to the plugins that I create, I have also spearheaded the company’s migration to TypeScript and React from vanilla JavaScript and have been involved in setting up an efficient continuous development and integration process to help deploy plugins efficiently and effectively.",
        "I have also switched to Linux since starting this new position and have been having an absolute blast learning how to interface with computers more efficiently with extremely powerful tools.",
        "While automating my workflows and trying to write optimally performant code, I have found myself wanting to go even deeper into understanding how things work under the hood. As a result, I have subsequently started learning a lower level programming language and have even used it to create a simple internal tool that assists in the plugin build process.",
        "I am always excited to learn new skills and look forward to building a lot more awesome software in future!",
    ]
    const skills = [
        "TypeScript",
        "React.js",
        "Node.js",
        "Linux",
        "Git",
        "BASH",
        "Rust",
    ]
    const experience = [
        {
            company: "Infinity Renewable Solutions",
            role: "Software Developer",
            dateRange: "October 2023 - present",
        },
        {
            company: "Valenture Institute (UCT Online High School)",
            role: "Learning Designer Physical Science",
            dateRange: "Sep 2021 - Sep 2023",
        },
        {
            company: "Norman Henshilwood High School:",
            role: "Mathematics teacher",
            dateRange: "Aug 2020 - Sep 2021",
        },
        {
            company: "Rosebank Progress College",
            role: "Physical Science and Mathematics teacher",
            dateRange: "June 2019 - June 2020",
        },
    ]
    const education = [
        {
            institution: "Hyperion Dev",
            field: "Full Stack Web Development Bootcamp",
            dateRange: "2023",
        },
        {
            institution: "Cape Peninsula University of Technology",
            field: "BEd: Mathematics and Physics",
            dateRange: "2019",
        },
        {
            institution: "City Varsity",
            field: "Diploma in Sound Engineering",
            dateRange: "2015",
        },
        {
            institution: "Westerford High School",
            field: "NSC Senior Certificate",
            dateRange: "2012",
        },

    ]
    return (
        <div>

        </div>
    )
}

export default AboutPage